import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateVocabu1781944205907 implements MigrationInterface {
    name = 'UpdateVocabu1781944205907'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_posts_user"`);
        await queryRunner.query(`ALTER TABLE "forum_comments" DROP CONSTRAINT "FK_forum_comments_post"`);
        await queryRunner.query(`ALTER TABLE "forum_comments" DROP CONSTRAINT "FK_forum_comments_user"`);
        await queryRunner.query(`ALTER TABLE "forum_post_likes" DROP CONSTRAINT "FK_forum_post_likes_post"`);
        await queryRunner.query(`ALTER TABLE "forum_post_likes" DROP CONSTRAINT "FK_forum_post_likes_user"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_notifications_user"`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" DROP CONSTRAINT "FK_user_vocabulary_progress_user"`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" DROP CONSTRAINT "FK_user_vocabulary_progress_vocabulary"`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" DROP CONSTRAINT "FK_user_vocabulary_progress_set"`);
        await queryRunner.query(`ALTER TABLE "vocabulary_practice_sessions" DROP CONSTRAINT "FK_vocabulary_practice_sessions_user"`);
        await queryRunner.query(`ALTER TABLE "vocabulary_practice_sessions" DROP CONSTRAINT "FK_vocabulary_practice_sessions_set"`);
        await queryRunner.query(`ALTER TABLE "vocabulary_practice_answers" DROP CONSTRAINT "FK_vocabulary_practice_answers_session"`);
        await queryRunner.query(`ALTER TABLE "vocabulary_practice_answers" DROP CONSTRAINT "FK_vocabulary_practice_answers_user"`);
        await queryRunner.query(`ALTER TABLE "vocabulary_practice_answers" DROP CONSTRAINT "FK_vocabulary_practice_answers_vocabulary"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_posts_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_forum_comments_post_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_forum_comments_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_forum_post_likes_post_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_forum_post_likes_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_vocabulary_progress_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_vocabulary_progress_vocabularyId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_vocabulary_progress_vocabSetId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_vocabulary_practice_sessions_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_vocabulary_practice_sessions_vocabSetId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_vocabulary_practice_answers_sessionId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_vocabulary_practice_answers_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_vocabulary_practice_answers_vocabularyId"`);
        await queryRunner.query(`ALTER TABLE "forum_post_likes" DROP CONSTRAINT "UQ_forum_post_likes_post_user"`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" DROP CONSTRAINT "UQ_user_vocabulary_progress_user_word"`);
        await queryRunner.query(`ALTER TABLE "exams" DROP COLUMN "duration"`);
        await queryRunner.query(`UPDATE "vocabulary_sets" SET "tag" = 'General' WHERE "tag" IS NULL OR btrim("tag") = ''`);
        await queryRunner.query(`ALTER TABLE "vocabulary_sets" ALTER COLUMN "tag" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."attempts_practice_mode_enum" RENAME TO "attempts_practice_mode_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."attempts_practicemode_enum" AS ENUM('grammar', 'listening_check', 'dictation')`);
        await queryRunner.query(`ALTER TABLE "attempts" ALTER COLUMN "practiceMode" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "attempts" ALTER COLUMN "practiceMode" TYPE "public"."attempts_practicemode_enum" USING "practiceMode"::"text"::"public"."attempts_practicemode_enum"`);
        await queryRunner.query(`ALTER TABLE "attempts" ALTER COLUMN "practiceMode" SET DEFAULT 'grammar'`);
        await queryRunner.query(`DROP TYPE "public"."attempts_practice_mode_enum_old"`);
        await queryRunner.query(`CREATE INDEX "IDX_c4f9a7bd77b489e711277ee598" ON "posts" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_274dc9abde99249ab89a47789b" ON "forum_comments" ("post_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_eb2baddd05b6ce30343a8f2531" ON "forum_comments" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e35c4f9cddf1ca64d0b39bfbb3" ON "forum_post_likes" ("post_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_64cfc415232095b4d94ff479a3" ON "forum_post_likes" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9a8a82462cab47c73d25f49261" ON "notifications" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a42a7f487761f517f874a36559" ON "user_vocabulary_progress" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_26ebd56c3009e19965688df8ea" ON "user_vocabulary_progress" ("vocabularyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1bec436a40ea287d732ad3fcc1" ON "user_vocabulary_progress" ("vocabSetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_de3f2b15bc547abf7cc5e9c8b7" ON "vocabulary_practice_sessions" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d9fdb6c09eefca838655db3480" ON "vocabulary_practice_sessions" ("vocabSetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a41643504729692677421e9182" ON "vocabulary_practice_answers" ("sessionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e3e8433d7dade8b41436874e5f" ON "vocabulary_practice_answers" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_111b484826fb65a9caab9935c8" ON "vocabulary_practice_answers" ("vocabularyId") `);
        await queryRunner.query(`ALTER TABLE "forum_post_likes" ADD CONSTRAINT "UQ_444af3ee105345c5f90d27b247a" UNIQUE ("post_id", "user_id")`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" ADD CONSTRAINT "UQ_c2de21ca3e7d1376f98e9601260" UNIQUE ("userId", "vocabularyId")`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_c4f9a7bd77b489e711277ee5986" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forum_comments" ADD CONSTRAINT "FK_274dc9abde99249ab89a47789b2" FOREIGN KEY ("post_id") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forum_comments" ADD CONSTRAINT "FK_eb2baddd05b6ce30343a8f25313" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forum_post_likes" ADD CONSTRAINT "FK_e35c4f9cddf1ca64d0b39bfbb37" FOREIGN KEY ("post_id") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forum_post_likes" ADD CONSTRAINT "FK_64cfc415232095b4d94ff479a3a" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" ADD CONSTRAINT "FK_a42a7f487761f517f874a365596" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" ADD CONSTRAINT "FK_26ebd56c3009e19965688df8ea1" FOREIGN KEY ("vocabularyId") REFERENCES "vocabulary"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" ADD CONSTRAINT "FK_1bec436a40ea287d732ad3fcc11" FOREIGN KEY ("vocabSetId") REFERENCES "vocabulary_sets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vocabulary_practice_sessions" ADD CONSTRAINT "FK_de3f2b15bc547abf7cc5e9c8b71" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vocabulary_practice_sessions" ADD CONSTRAINT "FK_d9fdb6c09eefca838655db3480c" FOREIGN KEY ("vocabSetId") REFERENCES "vocabulary_sets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vocabulary_practice_answers" ADD CONSTRAINT "FK_a41643504729692677421e9182c" FOREIGN KEY ("sessionId") REFERENCES "vocabulary_practice_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vocabulary_practice_answers" ADD CONSTRAINT "FK_e3e8433d7dade8b41436874e5f1" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vocabulary_practice_answers" ADD CONSTRAINT "FK_111b484826fb65a9caab9935c8c" FOREIGN KEY ("vocabularyId") REFERENCES "vocabulary"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "vocabulary_practice_answers" DROP CONSTRAINT "FK_111b484826fb65a9caab9935c8c"`);
        await queryRunner.query(`ALTER TABLE "vocabulary_practice_answers" DROP CONSTRAINT "FK_e3e8433d7dade8b41436874e5f1"`);
        await queryRunner.query(`ALTER TABLE "vocabulary_practice_answers" DROP CONSTRAINT "FK_a41643504729692677421e9182c"`);
        await queryRunner.query(`ALTER TABLE "vocabulary_practice_sessions" DROP CONSTRAINT "FK_d9fdb6c09eefca838655db3480c"`);
        await queryRunner.query(`ALTER TABLE "vocabulary_practice_sessions" DROP CONSTRAINT "FK_de3f2b15bc547abf7cc5e9c8b71"`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" DROP CONSTRAINT "FK_1bec436a40ea287d732ad3fcc11"`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" DROP CONSTRAINT "FK_26ebd56c3009e19965688df8ea1"`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" DROP CONSTRAINT "FK_a42a7f487761f517f874a365596"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "forum_post_likes" DROP CONSTRAINT "FK_64cfc415232095b4d94ff479a3a"`);
        await queryRunner.query(`ALTER TABLE "forum_post_likes" DROP CONSTRAINT "FK_e35c4f9cddf1ca64d0b39bfbb37"`);
        await queryRunner.query(`ALTER TABLE "forum_comments" DROP CONSTRAINT "FK_eb2baddd05b6ce30343a8f25313"`);
        await queryRunner.query(`ALTER TABLE "forum_comments" DROP CONSTRAINT "FK_274dc9abde99249ab89a47789b2"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_c4f9a7bd77b489e711277ee5986"`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" DROP CONSTRAINT "UQ_c2de21ca3e7d1376f98e9601260"`);
        await queryRunner.query(`ALTER TABLE "forum_post_likes" DROP CONSTRAINT "UQ_444af3ee105345c5f90d27b247a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_111b484826fb65a9caab9935c8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e3e8433d7dade8b41436874e5f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a41643504729692677421e9182"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d9fdb6c09eefca838655db3480"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_de3f2b15bc547abf7cc5e9c8b7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1bec436a40ea287d732ad3fcc1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_26ebd56c3009e19965688df8ea"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a42a7f487761f517f874a36559"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a8a82462cab47c73d25f49261"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_64cfc415232095b4d94ff479a3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e35c4f9cddf1ca64d0b39bfbb3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eb2baddd05b6ce30343a8f2531"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_274dc9abde99249ab89a47789b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c4f9a7bd77b489e711277ee598"`);
        await queryRunner.query(`CREATE TYPE "public"."attempts_practice_mode_enum_old" AS ENUM('grammar', 'listening_check', 'dictation')`);
        await queryRunner.query(`ALTER TABLE "attempts" ALTER COLUMN "practiceMode" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "attempts" ALTER COLUMN "practiceMode" TYPE "public"."attempts_practice_mode_enum_old" USING "practiceMode"::"text"::"public"."attempts_practice_mode_enum_old"`);
        await queryRunner.query(`ALTER TABLE "attempts" ALTER COLUMN "practiceMode" SET DEFAULT 'grammar'`);
        await queryRunner.query(`DROP TYPE "public"."attempts_practicemode_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."attempts_practice_mode_enum_old" RENAME TO "attempts_practice_mode_enum"`);
        await queryRunner.query(`ALTER TABLE "vocabulary_sets" ALTER COLUMN "tag" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "exams" ADD "duration" integer NOT NULL DEFAULT '60'`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" ADD CONSTRAINT "UQ_user_vocabulary_progress_user_word" UNIQUE ("userId", "vocabularyId")`);
        await queryRunner.query(`ALTER TABLE "forum_post_likes" ADD CONSTRAINT "UQ_forum_post_likes_post_user" UNIQUE ("post_id", "user_id")`);
        await queryRunner.query(`CREATE INDEX "IDX_vocabulary_practice_answers_vocabularyId" ON "vocabulary_practice_answers" ("vocabularyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_vocabulary_practice_answers_userId" ON "vocabulary_practice_answers" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_vocabulary_practice_answers_sessionId" ON "vocabulary_practice_answers" ("sessionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_vocabulary_practice_sessions_vocabSetId" ON "vocabulary_practice_sessions" ("vocabSetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_vocabulary_practice_sessions_userId" ON "vocabulary_practice_sessions" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_user_vocabulary_progress_vocabSetId" ON "user_vocabulary_progress" ("vocabSetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_user_vocabulary_progress_vocabularyId" ON "user_vocabulary_progress" ("vocabularyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_user_vocabulary_progress_userId" ON "user_vocabulary_progress" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_user_id" ON "notifications" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_forum_post_likes_user_id" ON "forum_post_likes" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_forum_post_likes_post_id" ON "forum_post_likes" ("post_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_forum_comments_user_id" ON "forum_comments" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_forum_comments_post_id" ON "forum_comments" ("post_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_posts_user_id" ON "posts" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "vocabulary_practice_answers" ADD CONSTRAINT "FK_vocabulary_practice_answers_vocabulary" FOREIGN KEY ("vocabularyId") REFERENCES "vocabulary"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vocabulary_practice_answers" ADD CONSTRAINT "FK_vocabulary_practice_answers_user" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vocabulary_practice_answers" ADD CONSTRAINT "FK_vocabulary_practice_answers_session" FOREIGN KEY ("sessionId") REFERENCES "vocabulary_practice_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vocabulary_practice_sessions" ADD CONSTRAINT "FK_vocabulary_practice_sessions_set" FOREIGN KEY ("vocabSetId") REFERENCES "vocabulary_sets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vocabulary_practice_sessions" ADD CONSTRAINT "FK_vocabulary_practice_sessions_user" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" ADD CONSTRAINT "FK_user_vocabulary_progress_set" FOREIGN KEY ("vocabSetId") REFERENCES "vocabulary_sets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" ADD CONSTRAINT "FK_user_vocabulary_progress_vocabulary" FOREIGN KEY ("vocabularyId") REFERENCES "vocabulary"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" ADD CONSTRAINT "FK_user_vocabulary_progress_user" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_notifications_user" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forum_post_likes" ADD CONSTRAINT "FK_forum_post_likes_user" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forum_post_likes" ADD CONSTRAINT "FK_forum_post_likes_post" FOREIGN KEY ("post_id") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forum_comments" ADD CONSTRAINT "FK_forum_comments_user" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forum_comments" ADD CONSTRAINT "FK_forum_comments_post" FOREIGN KEY ("post_id") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_posts_user" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
